### ISSUE TITLE
maze_makerについて

### ISSUE THREAD

**Issue by c0b21005c4** [c0b210377b/ProjExD2022#11]
https://github.com/c0b210377b/ProjExD2022/blob/29cb1811f52da76b1a3cac5262e19c48e1379477/ex03/maze.py#L59
この部分は迷路を作る部分なのでmaze_maker.pyで書いたほうがいいと思いました。せっかくファイルを分けているので、その部分の定義づけはしっかりしたほうがいいと思います。

**Comment by c0b210377b** [comment]
私の技量が足りず、混乱してしまい、やる気を損なうと感じたため、控えました
