### ISSUE TITLE
変数を作ったほうがいいと思います

### ISSUE THREAD

**Issue by c0b21005c4** [c0b210377b/ProjExD2022#19]
https://github.com/c0b210377b/ProjExD2022/blob/9b8e68f75d53c43fd15c35d9cb372a47467df1e6/ex05/fight_kokaton.py#L65
多分加速度として1.0005であったり1.0003をかけていると思うのですがここは変数にしたほうが汎用性が上がると思います。

**Comment by c0b210377b** [comment]
その通りですね
