### ISSUE TITLE
変数名がわかりづらい

### ISSUE THREAD

**Issue by c0b21005c4** [c0b210377b/ProjExD2022#2]
https://github.com/c0b210377b/ProjExD2022/blob/c66f7b383ee1fc5f71ea312cc7acb96e8449528e/ex01/alphabet.py#L4
変数名がよくわからなかったです。
簡潔にするといいと思いました。

**Comment by c0b210377b** [comment]
自分的にはわかりやすいものを書いたと感じましたが、わかりづらかったようなので、もう少しわかりやすい変数名にしようと思います。
