### ISSUE TITLE
これはなんだい？

### ISSUE THREAD

**Issue by suzukiyukito** [c0b210377b/ProjExD2022#20]
OSから何かを引っ張り出してくるんだろうけど、これが何なのかの説明が欲しい。
https://github.com/c0b210377b/ProjExD2022/blob/218af3427a7d814a9a5af504caa7beb464aec513/ex05/fight_kokaton.py#L6

**Comment by c0b210377b** [comment]
aliens.pyより引用致しました。
ファイルの中身に関するものでしょうが、細かいことはよく理解できていません。
