### ISSUE TITLE
揚げ音mp3

### ISSUE THREAD

**Issue by c0b21031** [c0b210377b/ProjExD2022#21]
https://github.com/c0b210377b/ProjExD2022/blob/218af3427a7d814a9a5af504caa7beb464aec513/ex05/fight_kokaton.py#L174

**Comment by c0b210377b** [comment]
???

**Comment by c0b21031** [comment]
いつ揚げた音が止まるのか気になる。コードをそこに置いた意図が知りたいお。

**Comment by c0b210377b** [comment]
チキンから離れたらです。
この場所に置けば、常に更新されるため、離れた瞬間に音がストップします
