### ISSUE TITLE
これ使ってる？

### ISSUE THREAD

**Issue by c0b21005c4** [c0b210377b/ProjExD2022#6]
https://github.com/c0b210377b/ProjExD2022/blob/06af578934ae708631c6b1b7ae555e53e8b0b57f/ex02/calc.py#L2
このコードではメッセージボックスを使っていないように思います。不必要なものなのでimportしなくても良いのではないかと思いました。

**Comment by c0b210377b** [comment]
全く気が付きませんでした。消しておけばよかったです。
